import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "./comps/banner/Banner";
import Categories from "./comps/categories/Categories";
import Feature from "./comps/feature/Feature";
import Footer from "./comps/footer/Footer";
import Header from "./comps/header/Header";
import Navbar from "./comps/navbar/Navbar";
import Product from "./comps/products/Product";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce Site</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Banner />
        <Feature />
        <Categories />
        <Product />
      </main>
    </div>
  );
}
